coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true