version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "wednesday"
    open-pull-requests-limit: 1
    target-branch: "dev"
    labels:
      - 'external-dependency'
      - 'brightlayer-ui'

  - package-ecosystem: "npm"
    directory: "/components"
    schedule:
      interval: "monthly"
      day: "wednesday"
    open-pull-requests-limit: 1
    target-branch: "dev"
    labels:
      - 'external-dependency'
      - 'brightlayer-ui'
      
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
      day: "wednesday"
    open-pull-requests-limit: 1
    target-branch: "dev"
    labels:
      - 'external-dependency'
      - 'brightlayer-ui'